// ─── Generated by Supabase CLI — do not edit the Database block manually ──────
// To regenerate: supabase gen types typescript --project-id albrrabsrueokiudrgjb > types/index.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      candidatos: {
        Row: {
          apellido: string
          created_at: string
          cv_url: string | null
          email: string | null
          estado: Database["public"]["Enums"]["candidato_estado"]
          id: string
          linkedin_url: string | null
          nombre: string
          telefono: string | null
          updated_at: string
        }
        Insert: {
          apellido: string
          created_at?: string
          cv_url?: string | null
          email?: string | null
          estado?: Database["public"]["Enums"]["candidato_estado"]
          id?: string
          linkedin_url?: string | null
          nombre: string
          telefono?: string | null
          updated_at?: string
        }
        Update: {
          apellido?: string
          created_at?: string
          cv_url?: string | null
          email?: string | null
          estado?: Database["public"]["Enums"]["candidato_estado"]
          id?: string
          linkedin_url?: string | null
          nombre?: string
          telefono?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      candidatos_vacantes: {
        Row: {
          candidato_id: string
          created_at: string
          etapa: Database["public"]["Enums"]["etapa_pipeline"]
          id: string
          notas: string | null
          updated_at: string
          vacante_id: string
        }
        Insert: {
          candidato_id: string
          created_at?: string
          etapa?: Database["public"]["Enums"]["etapa_pipeline"]
          id?: string
          notas?: string | null
          updated_at?: string
          vacante_id: string
        }
        Update: {
          candidato_id?: string
          created_at?: string
          etapa?: Database["public"]["Enums"]["etapa_pipeline"]
          id?: string
          notas?: string | null
          updated_at?: string
          vacante_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "candidatos_vacantes_candidato_id_fkey"
            columns: ["candidato_id"]
            isOneToOne: false
            referencedRelation: "candidatos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "candidatos_vacantes_vacante_id_fkey"
            columns: ["vacante_id"]
            isOneToOne: false
            referencedRelation: "vacantes"
            referencedColumns: ["id"]
          },
        ]
      }
      empresas: {
        Row: {
          contacto_email: string | null
          contacto_nombre: string | null
          contacto_telefono: string | null
          created_at: string
          id: string
          industria: string | null
          nombre: string
          updated_at: string
        }
        Insert: {
          contacto_email?: string | null
          contacto_nombre?: string | null
          contacto_telefono?: string | null
          created_at?: string
          id?: string
          industria?: string | null
          nombre: string
          updated_at?: string
        }
        Update: {
          contacto_email?: string | null
          contacto_nombre?: string | null
          contacto_telefono?: string | null
          created_at?: string
          id?: string
          industria?: string | null
          nombre?: string
          updated_at?: string
        }
        Relationships: []
      }
      vacantes: {
        Row: {
          created_at: string
          descripcion: string | null
          empresa_id: string
          estado: Database["public"]["Enums"]["vacante_estado"]
          id: string
          sueldo_maximo: number | null
          sueldo_minimo: number | null
          titulo: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          descripcion?: string | null
          empresa_id: string
          estado?: Database["public"]["Enums"]["vacante_estado"]
          id?: string
          sueldo_maximo?: number | null
          sueldo_minimo?: number | null
          titulo: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          descripcion?: string | null
          empresa_id?: string
          estado?: Database["public"]["Enums"]["vacante_estado"]
          id?: string
          sueldo_maximo?: number | null
          sueldo_minimo?: number | null
          titulo?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vacantes_empresa_id_fkey"
            columns: ["empresa_id"]
            isOneToOne: false
            referencedRelation: "empresas"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      candidato_estado: "activo" | "contratado" | "descartado"
      etapa_pipeline:
        | "prospecto"
        | "entrevista_inicial"
        | "entrevista_cliente"
        | "oferta"
        | "contratado"
        | "descartado"
      vacante_estado: "activa" | "pausada" | "cerrada" | "cancelada"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// ─── Enum aliases (derived from DB source of truth) ───────────────────────────

export type VacanteEstado = Database["public"]["Enums"]["vacante_estado"]
export type CandidatoEstado = Database["public"]["Enums"]["candidato_estado"]
export type EtapaPipeline = Database["public"]["Enums"]["etapa_pipeline"]

// ─── Row aliases ──────────────────────────────────────────────────────────────

export type EmpresaRow = Database["public"]["Tables"]["empresas"]["Row"]
export type VacanteRow = Database["public"]["Tables"]["vacantes"]["Row"]
export type CandidatoRow = Database["public"]["Tables"]["candidatos"]["Row"]
export type PipelineRow = Database["public"]["Tables"]["candidatos_vacantes"]["Row"]

// ─── Cotizador Types ───────────────────────────────────────────────────────────

export type NivelPuesto =
  | 'Operativo / Administrativo'
  | 'Especializado'
  | 'Jefatura / Senior'
  | 'Gerencial / Directivo'
  | 'Ingeniería / TI'

export interface CotizadorConfigNivel {
  nivel: NivelPuesto
  umbralMax: number
  factor: number
  garantiaDias: number
}

export interface CotizadorConfig {
  costoOperativoMensual: number
  capacidadVacantesMes: number
  margen: number
  niveles: CotizadorConfigNivel[]
  keywordsTI: string[]
}

export interface CotizadorInput {
  puesto: string
  sueldo: number
}

export interface CotizadorResult {
  puesto: string
  sueldo: number
  nivel: NivelPuesto
  factor: number
  garantia: number
  precio: number
  utilidad: number
  margenUtilidad: number
  // Desglose del cálculo
  costoBase: number
  costoPuesto: number
  margen: number
  esTI: boolean
}

// ─── CRM Leads Types ───────────────────────────────────────────────────────────

export type LeadOrigen =
  | 'sitio_web'
  | 'meta_ads'
  | 'google_ads'
  | 'linkedin_ads'
  | 'otro'

export type LeadEstado =
  | 'nuevo'
  | 'contactado'
  | 'en_negociacion'
  | 'ganado'
  | 'perdido'

export interface LeadRow {
  id: string
  nombre: string
  apellido: string
  empresa_razon_social: string
  telefono: string | null
  email: string | null
  sector: string | null
  origen: LeadOrigen
  estado: LeadEstado
  created_at: string
  updated_at: string
}

